baseURL = 'https://polymathmonkey.github.io/'
languageCode = 'en-us'
title = 'Forensic wheels'
theme = 'hugo-theme-relearn'
#relativeURLs = true
preserveTaxonomyNames = true
MetaDataFormat = "yaml"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true
pluralizeListTitles = false
copyright = "All text is licensed under a Creative Commons Attribution 4.0 International License."
showAllPostsArchive = true
ShowReadingTime = true
ShowShareButtons = true
ShowBreadCrumbs = true 
ShowCodeCopyButtons = true
ignoreLogs = ['warning-goldmark-raw-html']

# recommended theme parameter
author.name = 'Dirk'
include.errorlevel = 'warning'
image.errorlevel = 'warning'
externalLinkTarget = '_self'
link.errorlevel = 'warning'
openapi.errorlevel = 'warning'

# specific image effect for this showcase;
imageEffects.purple = false


[outputs]
  # `print` - activate the themes feature to print whole chapters or leaf pages
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  themeVariant = [ "auto", "neon" ]
  disableLandingPageButton = true
# Optional Params
  # This will match the navbarTitle to the section of the website
  dynamicTitles        = true
  # RSS icon that appear on the sidebar, next to the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Social media buttons that appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  categoriesByCount    = true
  includeReadingTime   = true
  # The set of favicons used are based on the write-up from this link:
  # https://github.com/audreyr/favicon-cheat-sheet
  # Please see the favicon partial template for more information
  loadFavicon          = false
  faviconVersion       = ""
  # Disable showing the social sharing links on blog posts
  socialShareDisabled = false

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[markup.goldmark.renderer]
  unsafe = true
  
ignoreLogs = ['warning-goldmark-raw-html']