baseURL = 'https://polymathmonkey.github.io/'
languageCode = 'en-us'
title = 'Forensic wheels'
theme = 'hugo-theme-relearn'
preserveTaxonomyNames = true
MetaDataFormat = "yaml"
enableRobotsTXT = true
enableEmoji = true
pluralizeListTitles = false
copyright = "All text is licensed under a Creative Commons Attribution 4.0 International License."
showAllPostsArchive = true
ShowShareButtons = true
ShowBreadCrumbs = true 
ShowCodeCopyButtons = true
ignoreLogs = ['warning-goldmark-raw-html']

# recommended theme parameter
include.errorlevel = 'warning'
image.errorlevel = 'warning'
externalLinkTarget = '_self'
link.errorlevel = 'warning'
openapi.errorlevel = 'warning'

# specific image effect for this showcase;
imageEffects.purple = false


[outputs]
  # `print` - activate the themes feature to print whole chapters or leaf pages
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']

[params]
  author.name = 'Dirk'
  themeVariant = [ "auto", "neon" ]
  disableLandingPageButton = true
  showVisitedLinks=true
  disableSearch = true
  alwaysopen = false
  disableSearchIndex = true
  disableSearchPage = true
  # Optional Params
  # This will match the navbarTitle to the section of the website
  dynamicTitles        = true
  # Please see the favicon partial template for more information
  loadFavicon          = false
  faviconVersion       = ""
  # Disable showing the social sharing links on blog posts
  socialShareDisabled = false

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[markup.goldmark.renderer]
  unsafe = true
  
